import type { Metadata } from "next";
import { cookies } from "next/headers";

import { ScrollArea, ScrollBar } from "@ziron/ui/components/scroll-area";
import { SidebarInset, SidebarProvider } from "@ziron/ui/components/sidebar";

import Header from "@/components/layout/header";
import { AppSidebar } from "@/components/layout/sidebar/app-sidebar";

import { getCurrentUser } from "@/features/auth/actions/user";
import { getCompanies } from "@/features/company/actions/queries";
import CompanyFormModal from "@/features/company/components/modal";
import { ShareModal } from "@/features/modal/share-modal";

export const metadata: Metadata = {
  title: "QR Code Generator",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";
  const session = await getCurrentUser();
  const companies = await getCompanies();

  return (
    <div className="w-full flex-1 bg-background" vaul-drawer-wrapper="">
      <SidebarProvider
        defaultOpen={defaultOpen}
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 52)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }
      >
        <AppSidebar data={companies} user={session.user} />
        <SidebarInset>
          <Header />

          <ScrollArea className="-mt-20">
            {children}
            <ScrollBar />
          </ScrollArea>
          <ShareModal />
        </SidebarInset>
      </SidebarProvider>
      <CompanyFormModal />
    </div>
  );
}
