import { Suspense } from "react";

import type { Metadata } from "next";

import { ShareModal } from "@/features/modal/share-modal";
import CompanyFormModal from "@/features/organization/components/modal";

import { RootSidebar } from "./_components/root-sidebar";

export const metadata: Metadata = {
  title: "QR Code Generator",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RootSidebar>
      {children}

      <Suspense>
        <ShareModal />
      </Suspense>

      <Suspense>
        <CompanyFormModal />
      </Suspense>
    </RootSidebar>
  );
}
